when:
  event: [push, pull_request]

steps:
  - name: test-payment-taler
    image: python:3.10

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      HOST: postgres

    commands:
      - apt-get update
      - apt-get install -y git gcc build-essential libpq-dev wget node-less

#      - apt-get install -y wkhtmltopdf

      - pip install --upgrade pip
      - pip install wheel setuptools
      - pip install psycopg2-binary

      - git clone --depth 1 --branch 18.0 https://github.com/odoo/odoo.git /odoo

      - pip install -r /odoo/requirements.txt

      - mkdir -p /mnt/custom_addons
      - mkdir -p /mnt/custom_addons/tops
      - mkdir -p /mnt/custom_addons/tops/payment_taler
      - cp -r . /mnt/custom_addons/tops/payment_taler

      - sleep 5

      - |
        python /odoo/odoo-bin \
          -d test_db \
          --db_host=$HOST \
          --db_user=$POSTGRES_USER \
          --db_password=$POSTGRES_PASSWORD \
          --addons-path=/odoo/addons,/mnt/custom_addons/tops \
          -i payment_taler \
          --test-enable \
          --test-tags taler \
          --stop-after-init \
          --log-level=test

services:
  - name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
